# Generated by Django 4.2 on 2023-04-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=32, unique=True)),
                ('e_mail', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('pc_name', models.CharField(max_length=32, unique=True)),
                ('serial', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=32, unique=True)),
                ('e_mail', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('pc_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('device_serial', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('user_last_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('user_first_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('user_e_mail', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('department_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('plant_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('status_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('admin_last_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('admin_first_name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('admin_e_mail', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_change', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.admin')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.device')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.plant')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
