# Generated by Django 4.2 on 2023-04-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0012_remove_card_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="title",
            field=models.CharField(default="Карточка ", max_length=32, null=True),
        ),
    ]
