# Generated by Django 4.2 on 2023-04-30 20:31

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0014_remove_card_device_alter_card_device_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="card",
            name="department",
        ),
        migrations.RemoveField(
            model_name="card",
            name="plant",
        ),
        migrations.RemoveField(
            model_name="card",
            name="status",
        ),
        migrations.RemoveField(
            model_name="card",
            name="user",
        ),
        migrations.AlterField(
            model_name="card",
            name="admin_last_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.admin",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="department_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.department",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="device_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.device",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="plant_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.plant",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="status_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.status",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="title",
            field=models.CharField(
                default=mainapp.models.card_number, max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="user_last_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.user",
            ),
        ),
    ]
